from pathlib import Path
import json, math
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.enums import TA_LEFT
OUT=Path('output/pdf');OUT.mkdir(parents=True,exist_ok=True)
pdfmetrics.registerFont(TTFont('Arial','C:/Windows/Fonts/arial.ttf'));pdfmetrics.registerFont(TTFont('ArialBold','C:/Windows/Fonts/arialbd.ttf'))
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodyTR',fontName='Arial',fontSize=9.4,leading=14,spaceAfter=9))
styles.add(ParagraphStyle(name='TitleTR',fontName='ArialBold',fontSize=22,leading=27,spaceAfter=18,textColor=colors.HexColor('#173f55')))
styles.add(ParagraphStyle(name='HeadTR',fontName='ArialBold',fontSize=13,leading=18,spaceAfter=10,textColor=colors.HexColor('#173f55')))
styles.add(ParagraphStyle(name='CellTR',fontName='Arial',fontSize=8.3,leading=11))
story=[]
def p(t):story.append(Paragraph(t,styles['BodyTR']))
def h(t):story.append(Paragraph(t,styles['HeadTR']))
def title(t):story.append(Paragraph(t,styles['TitleTR']))
def table(rows,widths):
 data=[[Paragraph(str(v),styles['CellTR']) for v in row] for row in rows]
 tb=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT');tb.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#dfedf3')),('GRID',(0,0),(-1,-1),.4,colors.HexColor('#bac7ce')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));story.extend([tb,Spacer(1,12)])
def page():story.append(PageBreak())
title('3,3 V buck tasarımı\nve kart şematik denetimi'.replace('\n','<br/>'))
p('KiCad 10 • 10 Eylül 2026 • Tasarım yükü: 1 A • Giriş: PD_VOUT, 5–28 V')
h('Sonuç ve kapsam')
p('AOZ1284PI kontrol ağı tamamlandı: R41=12,7 kΩ, C19=18 nF; EN için U6 TL431BIDBZR ve R43=1 kΩ / 2 W eklendi. U5’in dokuz elektriksel bağlantısı netlist üzerinden doğrulandı. Exposed pad VIN’e bağlıdır. Ana 5 A çıkış akımı bu buck üzerinden geçmez.')
p('Diğer sayfalarda yedi kopuk bağlantı grubu düzeltildi, Q3/Q4 için gerçek SO8 pin eşlemesi oluşturuldu ve uygun olmayan bazı güç elemanı ayak izleri büyütüldü. Kart üretime hazır değildir: ana MOSFET sürüş uyumluluğu, kesin güç elemanı seçimi ve TFT bilgileri açık kalıyor.')
table([['Kontrol','Sonuç'],['Net grupları','22 / 22 geçti; U5, EN referansı, I²C, INT, şönt ve MOSFET ortak padleri'],['ERC başlangıç','15 hata + 278 uyarı = 293'],['ERC sonuç','7 hata + 275 uyarı = 282'],['PCB','Dosya boş: yerleşim, iz, bakır, ısıl ve DRC doğrulaması yok'],['Değişen dosyalar','powergeneration, usb_pd_controller, userinterface, powersensing; Power_Supply_Custom sembol kütüphanesi'],['POWER OUTPUT','J4 geliştirme aşamasında; bağlantıları değiştirilmedi']],[130,377])
p('Bu rapor mevcut dosyaların denetimidir. Ölçülmüş verim, faz marjı veya sıcaklık sonucu değildir. Önceki UNRESOLVED notlarının yerine hesaplanmış kontrol ağı kullanılmıştır; gerçek parça eğrileri ve prototip doğrulaması ayrı kalemlerdir.')
h('Kanıt dosyaları')
p('reports/review-20260910/ altında before/ yedeği, hesap özeti, before.xml, after.xml, ERC raporları, net-checks.json ve SVG çıktıları bulunur. Eski reports/buck-20260910 raporundaki EN/COMP durumu bu raporla güncellenmiştir.')
page();title('U5 — pin bazında karşılaştırma')
p('DATASHEET VALUE: AOS AOZ1284PI Rev.1.1, Mart 2025, pin tablosu s.2. Aşağıdaki uygulama bağlantıları KiCad XML netlistinden kontrol edilmiştir.')
table([['Pin / işlev','Datasheet bağlantı amacı','Şematikte uygulama'],['1 / LX','Anahtarlama çıkışı','U5.1 → L1.1 + D2.K + C17.2 → LX_SW (yerel)'],['2 / BST','LX’e 100 nF bootstrap','U5.2 → C17.1; C17.2 → LX_SW. 100 nF / 16 V'],['3 / GND','Toprak','U5.3 → GND güç sembolü → GND'],['4 / FSW','Frekans direnci','U5.4 → R38 100 kΩ → GND'],['5 / COMP','Kompanzasyon R-C ağı','U5.5 → R41 12,7 kΩ → C19 18 nF → GND'],['6 / FB','0,8 V geri besleme','U5.6 → R39 alt ucu + R40 üst ucu → FB_3V3; R39 üstü +3.3V'],['7 / SS','Soft-start kondansatörü','U5.7 → C18 10 nF → GND'],['8 / EN','İzin girişi','U5.8 → U6.K/REF + R42 + R43 → EN_CTRL, nominal 2,495 V'],['EP / VIN (pad 9)','Besleme; GND değildir','U5.9 → C12/C13/C14 üst uçları → PD_VOUT']],[66,137,304])
h('Destek ağı ve paket')
p('U6: pin 1=K, pin 2=REF, pin 3=A. K ve REF birlikte EN_CTRL; A=GND. R43 PD_VOUT–EN_CTRL, R42 EN_CTRL–GND. +3.3V hattı L1.2, C15.1, C16.1 ve R39.1 üzerinde birleşir.')
p('U5: SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.71x3.7mm korundu. Gövde, pitch ve exposed-pad ölçüleri SO8_EP1 ile uyumlu; KiCad pad 9 VIN’dir. Kütüphane lehim padleri AOS önerilen land pattern ile birebir aynı değildir; üretim land-pattern incelemesi gereklidir. VIN termal bakırını GND’ye bağlamayın.')
page();title('Güç katı hesapları')
h('DATASHEET VALUE')
p('Çalışma girişi 3–36 V; FB nominal 0,8 V. Harici Schottky gerekir. Rf[kΩ]=50000/f[kHz]−5; tabloda 100 kΩ için 500 kHz yer alır. Minimum on-time 150 ns. Sayfa 8–12 tasarım denklemleri kullanılmıştır.')
h('CALCULATED VALUE')
table([['Büyüklük','VIN=5 V','VIN=28 V'],['İdeal D=Vo/Vin','0,6600 (%66)','0,11786 (%11,79)'],['ΔIL; L=22 µH, f=476,19 kHz','0,1071 A','0,2779 A'],['Normal yükte IL,peak','1,0536 A','1,1389 A'],['On-time D/f','1386 ns','247,5 ns'],['Diyot ortalama I=Io(1−D)','0,340 A','0,8821 A'],['Cin RMS akımı','0,4737 A','0,3224 A']],[235,136,136])
p('ΔIL=Vo(1−Vo/Vin)/(fL). L toleransı −%20 alınırsa 28 V’ta ripple 0,3473 A, peak 1,1737 A olur. Isat≥2 A seçimi normal yükte yaklaşık %70 marj verir; Irms≥1,5 A istenir. Frekans için ek −%20 mühendislik hassasiyetinde ripple 0,4342 A, peak 1,2171 A olur. Bu köşe 100 kΩ için üretici garantisi değildir.')
p('Diyot: VRRM girişin 28 V üstünde olmalı; seçilen gereksinim 60 V / 2 A Schottky. Peak akım normal köşede ≥1,174 A; ters gerilim çınlaması PCB üzerinde ölçülmelidir. Güç kaybı yaklaşık 0,882×VF: VF=0,5 V varsayımında 0,441 W. Bu VF, seçilmiş parçanın datasheet değeri değildir.')
h('ENGINEERING CHOICE')
p('100 kΩ / yaklaşık 500 kHz ve 22 µH, boyut ve anahtarlama kaybı arasında tercih edildi. Denklemden 476,19 kHz kullanımı ripple hesabını tablodaki 500 kHz’e göre daha ihtiyatlı yapar. 28 V’ta on-time yeterlidir; üst frekans köşesi prototipte doğrulanır. Gerçek duty, diyot ve anahtar kayıplarıyla ideal sonuçtan büyüktür.')
p('AOZ akım limiti normal 1 A yük gereksiniminden yüksektir; 2 A Isat şartı kısa devre dayanımı garantisi değildir. L1 ve D2 kesin MPN/ayak izi seçilmeden üretim yapılmamalıdır.')
page();title('Kondansatör, FB ve soft-start')
table([['Eleman','ENGINEERING CHOICE','CALCULATED VALUE / kabul şartı'],['C12 + C13 + C14','2×10 µF / 50 V X7R + 100 nF / 50 V','28 V bias ve tolerans sonrası ana bank ≥10 µF etkili'],['C15 + C16','2×47 µF / 10 V X7R','3,3 V bias sonrası ≥44 µF etkili; kompanzasyon bu alt sınırla hesaplandı'],['C17','100 nF / 16 V','BST–LX; bootstrap farkı için seçilen gerilim payı'],['R39 / R40','10 kΩ / 3,20 kΩ; %0,1','Vo=0,8(1+10/3,2)=3,300 V'],['C18','10 nF','tSS=0,8 C/ISS=3,2 ms; ISS=2–3 µA ile 2,67–4 ms']],[91,185,231])
p('Cin: ΔVin=Io·D(1−D)/(f·Cin). Etkili 10 µF ve 476,19 kHz için en kötü D=0,5 noktasında 52,5 mV; 5 V’ta 47,1 mV, 28 V’ta 21,8 mV. Maksimum RMS gereksinimi 0,5 A’dır. Giriş kablosu/PD anahtarlama sıçramaları bu ideal hesaba dahil değildir.')
p('Cout: ΔVo≈ΔIL·[ESR+1/(8fC)]. Etkili 44 µF, L−%20 için kapasitif bileşen 2,07 mV; ESR katkısı ayrıca eklenir. Ripple RMS akımı yaklaşık 0,100 A’dır. Bu sonuçlar Wi-Fi yük adımı regülasyonunu kanıtlamaz.')
p('FB toleransı: referans %±1,5 ve dirençlerin %±0,1 uçlarıyla, bias akımı hariç yaklaşık 3,246–3,355 V. FB giriş akımı 1 µA üst sınırda üst direnç üzerinde yaklaşık 10 mV ek hata oluşturabilir. 3,3 V tam kesinlikte garanti edilmez.')
p('MLCC üzerindeki yazılı değer etkili kapasite değildir. 1210 ayak izi ve 50 V etiketi tek başına bias koşulunu doğrulamaz. Kesin MPN’nin DC-bias, sıcaklık ve tolerans eğrileriyle ≥10 µF / ≥44 µF şartları kapatılmalıdır. Yerel yük bypass kapasitörleri korunmuştur.')
h('Normal çalışma ile arıza koşulunu ayırma')
p('Bu rail yaklaşık 0,4 A beklenen peak yük için 1 A üzerinden boyutlandırıldı. Ana terminaldeki 5 A ayrı güç yoludur. Endüktör doyumu, diyot surge değeri ve AOZ kısa devre davranışı kesin parça ve PCB ile birlikte doğrulanmalıdır.')
page();title('COMP ve EN tasarım kararı')
h('COMP — hesaplanmış başlangıç ağı')
p('CALCULATED VALUE: RL=3,3 Ω, Co=44 µF, fc=10 kHz; fp1=1/(2πCoRL)=1096 Hz. Uygulama bölümündeki GEA=200 µA/V, GCS=4,5 A/V ile Rc=fc·(Vo/VFB)·2πCo/(GEA·GCS)=12,67 kΩ. Cc=1,5/(2πRc·fp1)=17,2 nF.')
p('ENGINEERING CHOICE: R41=12,7 kΩ, C19=18 nF. Kompanzasyon sıfırı yaklaşık 696 Hz. Elektriksel tablodaki GEA=170 µA/V ile aynı ağın tahmini fc değeri 8,52 kHz’dir; her ikisi fSW/10 altında kalır. Sayfa 12’deki ilk Cc denkleminin 1,5 katsayısı kullanıldı. Ardından verilen sade denklem bu katsayıyı içermez; hesap seçimimiz burada açıktır.')
p('Co 94 µF olursa aynı yaklaşım fc≈4,0–4,7 kHz verir. Bu aralık, kondansatörün gerçekte 44–94 µF olduğuna dair üretici garantisi değildir. Loop gain ve yük adımı ölçümü yapılmadı; “COMP seçilmedi” yerine “ağ hesaplandı, dinamik doğrulama bekliyor” durumu geçerlidir.')
h('EN — bağımsız 2,495 V bias')
p('DATASHEET VALUE: AOZ EN açık eşiği 1,2 V; kapalı eşiği 0,4 V; mutlak limit 6 V. PD_VOUT’a doğrudan bağlantı 28 V koşulunda uygun değildir. TI TL431BIDBZR DBZ pinleri K1/REF2/A3’tür; regülasyon için en kötü minimum katot akımı 1 mA’dır.')
p('ENGINEERING CHOICE: R43=1 kΩ / 2 W, U6 şöntü 2,495 V, R42=100 kΩ. 5 V’ta besleme akımı 2,505 mA, R42 akımı 24,95 µA; yaklaşık 2,48 mA şönt bütçesi kalır (EN giriş akımı hariç). 28 V’ta R43 kaybı 0,651 W; U6 kaybı yaklaşık 64 mW. R43 için gerçek 2 W parça seçilmeli; 2512 paketi otomatik olarak 2 W anlamına gelmez.')
p('Bu yöntem sürekli açık bias sağlar; harici UVLO işlevi değildir. EN giriş akımının garantili üst sınırı AOZ tablosunda verilmediğinden 5 V köşesinde ölçüm gerekir. TL431’e ek kapasitif yük konulmadı. Girişin 4,5 V altındaki rampası/düşüşü ve bootstrap başlangıcı ayrıca incelenmelidir; 5–28 V kararlı çalışma isteğiyle sınırlı hesap yapıldı.')
page();title('Kartın diğer blokları')
table([['Blok','Bulgu ve yapılan işlem'],['USB PD','R4–R7 pull-up uçları, R8 INT ve R11 USB_VBUS boşlukları kapatıldı. CC1/CC2 net eşlemesi mevcut. C3/C8 50 V gereksinimi ve daha makul paketler verildi; C4 1 µF / 10 V yapıldı.'],['Ana MOSFET’ler','Q3/Q4: G4, S1/2/3, D5/6/7/8 düzeltildi; SOIC8 ayak izi atandı. Ortak-source bağlantısı korundu. IRF7855 Rds yalnız 10 V VGS’de belirtilmiş; AP33772S sürücüsüyle uygunluğu kanıtlanmadı. Bu kritik parça seçimi açık.'],['Güç ölçümü','5 mΩ RShunt ve girişteki R11 için 1 W / 2512 gereksinimi girildi. 5 A’da her biri 25 mV / 0,125 W; gerçek parçanın Kelvin yerleşimi ve TCR seçimi gerekli. INA228 Vin+ PD_VOUT, Vin−/VBUS OUT_POS.'],['MCU / RTC','3,3 V, reset/boot ve RTC I²C netleri incelendi. GPIO8 pull-up mevcut. RTC yedek pil kimyası/şarj ayarı doğrulanmadı. TFT’nin GPIO4/5/15 üzerindeki başlangıç etkisi panel bilgisine bağlı.'],['Encoder / TFT','Encoder A=GPIO22, B=GPIO23, SW=GPIO21; 10 kΩ pull-up ve GND ortakları mevcut. Q6 drain–BL_SINK boşluğu kapatıldı. BACKLIGHT_3V0 kaynaksız; TFT modeli ve LED akımı olmadan bağlanmadı.'],['USB / mekanik','D+/D− etiketleri ve çift yüz USB2 uçları incelendi. USB konektörünün ayak izi seçilmemiş. Encoder mekanik montaj ölçüleri ve sembol kütüphane farkı açık. ESD elemanı/yerleşimi tamamlanmalı.']],[108,399])
h('ERC’de kalanlar')
p('7 hata: beş power_pin_not_driven (VCC, GND, +3.3V, VBACKUP, PD_VOUT) ve J4’ün iki boş pini. Güç bayrakları fiziksel güç yolu uygunluğunu kanıtlamadığı için eklenmedi. 275 uyarı: 267 grid dışı uç, 6 sarkan tel, 1 tek pinli BACKLIGHT_3V0 etiketi, 1 encoder kütüphane farkı. Grid dışı olmak tek başına kopukluk değildir; netlist kontrolü ayrı yapıldı.')
p('Tüm sayfalar dışa aktarıldı; ana fonksiyon sayfaları görsel olarak incelendi. Proje boş PCB içerdiğinden bakır akım taşıma, RF keepout, termal via, creepage ve yerleşim sonuçları verilmez. Her parça için kapsamlı BOM doğrulaması tamamlanmış değildir.')
page();title('POWER OUTPUT — geliştirme notu')
p('Mevcut şemada J4 yalnız iki pinli terminaldir; iki pin de boş. POWER SENSING sayfasında PD_VOUT → 5 mΩ şönt → OUT_POS yolu var. J4.1’i OUT_POS’a, J4.2’yi GND’ye bağlamak doğrudan PD geçişli çıkış oluşturur; bağımsız ayarlı laboratuvar güç katı oluşturmaz. Geliştirme niyetiniz nedeniyle terminal otomatik bağlanmadı.')
table([['Hedef','Gereken mimari'],['PD gerilimini terminale aktarmak','PD_VOUT → korumalı çıkış anahtarı → ölçüm şöntü → OUT_POS → J4.1; J4.2 GND. Kesin anahtar/şönt sırası ölçüm amacına göre seçilir.'],['Sürekli ayarlı CV/CC çıkış','Ayrı güç dönüştürücü + gerilim/akım kontrol döngüleri + akım algılama + çıkış kesme gerekir. INA228 ölçüm içindir; tek başına CC regülatörü değildir.'],['Girişten düşük çıkış','Buck güç katı uygun olabilir; maksimum çıkışta dropout payı gerekir.'],['Girişin üstüne de çıkmak','Buck-boost veya uygun iki kademe gerekir. Güç ve termal bütçe yeniden boyutlandırılır.']],[130,377])
p('5 A her gerilimde otomatik kullanılabilir değildir. 28 V×5 A=140 W yalnız ilgili adaptör/PD sözleşmesi, kablo, konektör ve termal koşullar sağlanırsa girişte mümkündür. İç 3,3 V elektroniği ve dönüşüm kayıpları da bu bütçeden pay alır; terminalde tam 140 W garanti edilemez.')
p('Önemli sistem riski: ESP32 beslemesi PD_VOUT’tan geliyor. PD koruması çıkış MOSFET’ini kapatırsa MCU da kapanabilir; AP33772S’nin yeniden istek gerektiren durumlarında kurtarma davranışı planlanmalıdır. FA02 varsayılan 5 V seçimi başlangıca yardımcı olur, her arıza kurtarmasını garanti etmez. Bağımsız kontrol beslemesi veya doğrulanmış yeniden başlatma stratejisi gerekir.')
p('POWER OUTPUT için sıradaki tasarım girdileri: hedef çıkış gerilim aralığı, sürekli/peak akım, CV/CC hassasiyeti, çıkış kapalıyken sızıntı/deşarj, harici ters besleme toleransı. Donanım OCP/OVP ve ters akım koruması, terminale enerji vermeden önce tamamlanmalıdır.')
page();title('Güncel buck şeması ve kaynaklar')
im=Path('reports/review-20260910/svg/masaüstü güç kaynağı-POWER GENERATION.png')
story.append(Image(str(im),width=507,height=359));story.append(Spacer(1,12))
h('Birincil kaynaklar')
sources=[('AOS AOZ1284PI, Rev.1.1, Mart 2025; s.2–3, 8–13','https://www.aosmd.com/sites/default/files/res/datasheets/AOZ1284PI.pdf'),('TI TL431, Rev.S; DBZ pinleri ve minimum katot akımı','https://www.ti.com/lit/ds/symlink/tl431.pdf'),('Diodes AP33772S, DS46176 Rev.10-2; s.3,5–6,10','https://www.diodes.com/datasheet/download/AP33772S.pdf'),('Infineon IRF7855; pin/paket ve VGS/Rds şartları','https://www.infineon.com/assets/row/public/documents/24/49/infineon-irf7855-datasheet-en.pdf'),('TI INA228','https://www.ti.com/lit/ds/symlink/ina228.pdf'),('Espressif ESP32-C6-WROOM-1, v1.4','https://www.espressif.com/sites/default/files/documentation/esp32-c6-wroom-1_wroom-1u_datasheet_en.pdf'),('Micro Crystal RV-3028-C7','https://www.microcrystal.com/fileadmin/Media/Products/RTC/Datasheet/RV-3028-C7.pdf')]
for name,url in sources:p(f'<link href="{url}" color="#16658a">{name}</link>')
def footer(c,doc):
 c.setFont('Arial',8);c.setFillColor(colors.HexColor('#61717b'));c.drawString(44,25,'Şematik tasarım incelemesi • 10.09.2026 • Prototip doğrulaması gerekli');c.drawRightString(551,25,str(doc.page))
doc=SimpleDocTemplate(str(OUT/'AOZ1284PI_kart_inceleme.pdf'),pagesize=(595.28,841.89),leftMargin=44,rightMargin=44,topMargin=43,bottomMargin=44,title='AOZ1284PI pin karşılaştırması ve kart denetimi',author='Codex')
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT/'AOZ1284PI_kart_inceleme.pdf')
